### ISSUE TITLE
any plans to support Aes256?

### ISSUE THREAD

**Issue by seymour-bootay** [martindisch/aes-ccm#4]
Do you plan on supporting Aes256?

**Comment by DurandA** [comment]
CCM mode is only defined for block ciphers with a block length of 128 bits. If what you want is just AES256, have a look at [RustCrypto](https://github.com/RustCrypto/block-ciphers).

**Comment by seymour-bootay** [comment]
Sorry I was talking about key length.

**Comment by martindisch** [comment]
Ah alright, sorry about the misunderstanding. TinyCrypt only implements the case using 128 bit keys and since we basically only ported that, this is what we ended up with. It might not be that hard to also offer the 192 bit or 256 bit options, but I'm not familiar enough with the topic to be able to quickly do that and I don't have the time to go study the RFC in sufficient detail either.

**Comment by DurandA** [comment]
> Sorry I was talking about key length.

~CCM is only defined with AES key length of 128 bits which means there is no standardized CCM mode for 256 bits.~

**Edit**: AES-CCM can use 128, 192 or 256 bits keys. I am still looking for proper test vectors.

**Comment by seymour-bootay** [comment]
Thanks. I re-read SP 800-38C  last night and this morning to verify I did not miss something specifying only 128 bit keys.  Let me know if you want me to test something out.  I might play around with the library this weekend to see if I can get it working if I have some free time.

**Comment by DurandA** [comment]
From a quick readout of 800-38C I think that it requires no further changes required for 192 and 256 bits keys apart from the key length. Both WolfSSL/WolfCrypt and OpenSSL support _AES-192-CCM_ and _AES-256-CCM_ so testing should be easy.

@seymour-bootay Are you willing to make a PR? I can do it otherwise.

@martindisch Can you re-open this issue?

**Comment by seymour-bootay** [comment]
I can probably do a PR tonight.

**Comment by martindisch** [comment]
Great, looking forward to it.

**Comment by martindisch** [comment]
Thanks to recent contributions, this crate now supports AES-256-CCM.
